name: Am an Epic
description: Describe this issue template's purpose here.
title: Am an Epic
type: Epic
body:
    - type: markdown
      attributes:
          value: This is going to be an amazing feature.
    - type: checkboxes
      id: def-of-done
      attributes:
        label: Will this be super cool
        description: Please use this checklist to indicate standards.
        options:
          - label: This will definitely be cool
    - type: dropdown
      id: accessibility
      attributes:
        label: Accessibility
        description: What frontend work (if any) will this Epic require?
        options:
          - 'Requires a brand new UI'
          - 'Requires frontend work in the Storefront or outside the Admin'
          - 'Requires frontend work -only- in the Admin'
          - 'Backend-only work required'
        default: 0
      validations:
        required: true
