name: Am an Epic
description: Describe this issue template's purpose here.
title: Am an Epic
type: Epic
body:
    - type: markdown
      attributes:
          value: This is going to be an amazing feature.
    - type: checkboxes
      id: def-of-done
      attributes:
        label: Will this be super cool
        description: Please use this checklist to indicate standards.
        options:
          - label: This will definitely be cool
    - type: dropdown
      id: version
      attributes:
        label: Version
        description: What version of our software are you running?
        options:
          - 1.0.2 (Default)
          - 1.0.3 (Edge)
        default: 0
      validations:
        required: true
