name: Add needs-triage label to new PullRequests and Issues

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  needs-triage:
    runs-on: ubuntu-24.04
    steps:
      - name: Has labels
        id: applied-labels
        #if:  github.event.issue.labels.*.name
        #if: ${{ contains(github.event.issue.labels.*.name) && startsWith(github.event.issue.labels.*.name, 'component')) }}
        #if: ! startsWith(github.event.issue.labels.*.name, 'component')
        #run: echo "applied_labels=fromJSON(github.event.issue.labels.*.name)" >> $GITHUB_ENV #prints out "fromJSON(github.event.issue.labels.*.name)"
        run: echo "${{ toJSON(github.event.issue.labels.*.name) }}"
        
        #run: echo "${{ join(github.event.issue.labels.*.name) }}" #not sure how join works
        ##failed: if: contains(fromJSON(github.event.issue.labels.*.name), startsWith(fromJSON(github.event.issue.labels.*.name), 'component'))
      - name: whats it even doing
        #if: startsWith(github.event.issue.labels.*.name, 'component')
        run: echo "${{ startsWith(github.event.issue.labels.*.name, 'domain') }}"
        
        
        #- name: any domain 
        #run: echo "${{ startsWith(fromJSON(github.event.issue.labels.*.name), 'domain') }}"

      - name: Add needs-triage label
        uses: srvaroa/labeler@v1.13.0
        if: ! startsWith(github.event.issue.labels.*.name, 'domain') #not case sensitive
        #if: contains(fromJSON('["Domain/Discovery", "Domain/Admin"]'), github.event.issue.labels.*.name)
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          config_path: .github/labeler-needs-triage.yml
