name: Add needs-triage label to new PullRequests and Issues

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  needs-triage:
    runs-on: ubuntu-24.04
    steps:
      - name: Has labels
        #if:  github.event.issue.labels.*.name
        #if: ${{ contains(github.event.issue.labels.*.name) && startsWith(github.event.issue.labels.*.name, 'component')) }}
        #if: ! startsWith(github.event.issue.labels.*.name, 'component')
        run: echo "${{ toJSON(github.event.issue.labels.*.name) }}" #prints out list of labels
        
      - name: any domain 
        run: echo "${{ startsWith(fromJSON(github.event.issue.labels.*.name), 'domain')) }}"

      - name: Add needs-triage label
        uses: srvaroa/labeler@v1.13.0
        if: ! startsWith(github.event.issue.labels.*.name, 'domain') #not case sensitive
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          config_path: .github/labeler-needs-triage.yml
