name: Create issues from .md files

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  create-subissues:
    runs-on: ubuntu-latest

    steps:
      - run: gh issue create --body-file ../ISSUE_TEMPLATE/epics/test.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
