name: Create issues from .md files

on:
  workflow_dispatch:
  push:
    branches:
      - trunk

permissions:
  issues: write

jobs:
  create-subissues:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO: ${{ github.repository }}

    steps:
      - name: Create list of all markdown files from codex
        run: |
          FILES=$(gh api --jq '.[].name' /repos/$REPO/contents/.github/ISSUE_TEMPLATE/codex | grep '.md' )
          {
            echo "FILELIST<<EOF"
            echo "${FILES}"
            echo "EOF"
          } >> "$GITHUB_ENV"

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create issue for each markdown file
        run: |
          for file in $FILELIST; do
            # set title to file name
            TITLE="${file}"
            gh issue create --title "$TITLE" --body-file "/repos/$REPO/contents/.github/ISSUE_TEMPLATE/codex/${file}"
          done
