name: Run playwright via shopware-cli

on:
  workflow_dispatch:

jobs:
  visual-admin:
    runs-on: ubuntu-24.04

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          
      - name: Install shopware-cli
        uses: shopware/shopware-cli-action@v3

      - name: Create Shopware project
        run: shopware-cli project create swcli latest --no-interaction --no-audit

      - name: Build project for CI
        run: shopware-cli project ci swcli

      - name: Start Docker services
        working-directory: swcli
        run: docker compose up -d
