name: Run playwright via shopware-cli

on:
  workflow_dispatch:

jobs:
  visual-admin:
    runs-on: ubuntu-24.04

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Clone shopware/shopware
        uses: actions/checkout@v4
        with:
          repository: shopware/shopware
          path: shopware-platform
          
      - name: Install shopware-cli
        uses: shopware/shopware-cli-action@v3

      - name: Create Shopware project
        run: shopware-cli project create swcli --no-interaction --ci github

      - name: Build project for CI
        run: shopware-cli project ci swcli

      - name: Copy compose files and tests directory into swcli
        run: |
          cp shopware-platform/compose.yaml swcli/compose.yaml
          cp -R shopware-platform/tests swcli/tests
          ls swcli

      - name: Start Docker services
        run: docker compose up -d
