name: Create subissues for Epic issues

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  create-subissues:
    runs-on: ubuntu-latest
    if: github.event.issue.type.name == 'Epic'
    env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Save issue URL to env
        run: |
          echo "PARENT_NUM=${{ github.event.issue.number }}" >> $GITHUB_ENV
          echo "SUBISSUE_DIR=/repos/${{ github.repository }}/contents/.github/ISSUE_TEMPLATE/${{ github.event.issue.type.name }}" >> $GITHUB_ENV
          echo "TEST_API=/repos/${{ github.repository }}/issues/$PARENT_NUM/sub_issues" >> $GITHUB_ENV
      
      - name: Find files in correct subdirectory
        run:  | 
          echo "MY_FILELIST=$(gh api /repos/WorkflowsCI/prose-test/contents/.github/ISSUE_TEMPLATE/Epic --jq '.[].name') >> $GITHUB_ENV

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get add subissue api
        run: |
          echo "ADD_SUBISSUE_API=/repos/${{ github.repository }}/issues/$PARENT_NUM/sub_issues" >> $GITHUB_ENV
          echo "ADD_SUBISSUE_API2=${{ github.event.issue.url }}/sub_issues" >> $GITHUB_ENV

      - name: Create issue from file
        run: echo "CHILD=$(gh issue create --title "Autocreated subissue with type task" --body-file ".github/ISSUE_TEMPLATE/${{ github.event.issue.type.name }}/test.md")" >> $GITHUB_ENV 
      
      - name: Get child issue Number
        run: echo "CHILD_NUM=$(gh issue view $CHILD --json number --jq '.number')" >> $GITHUB_ENV

      - name: Get child issue database ID 
        #see: https://jessehouwing.net/create-github-issue-hierarchy-using-the-api/
        run: echo "CHILD_ID=$(gh api /repos/${{ github.repository }}/issues/$CHILD_NUM --jq .id)" >> $GITHUB_ENV
          
      - name: Attach child issue to Epic
        run: gh api -X POST $ADD_SUBISSUE_API -F sub_issue_id=$CHILD_ID

      - name: Set subissue type to Task
        run: gh api -X PATCH /repos/${{ github.repository }}/issues/$CHILD_NUM --field type=Task

      # Source - https://stackoverflow.com/a
      # Posted by Charles
      # Retrieved 2026-01-07, License - CC BY-SA 4.0
      
      - name: Finding files
        id: finding-files        
        run: |

          declare -a myFiles=$(find $SUBISSUE_DIR -type f -name '*.md')
          echo $myFiles >> $GITHUB_ENV

          for file in $SUBISSUE_DIR; do
            if [[ -f "$file" ]]; then
              echo 'FILELIST<<EOF'
              find $SUBISSUE_DIR -name '*.md' -print 
              echo EOF
              echo $FILELIST >> "$GITHUB_ENV"
            fi
          done

      - name: Do something with each file
        run: |
          for i in $FILELIST; do
            echo "Do something with file ${i}"
          done  

