name: Create subissues for Epic issues

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  create-subissues:
    runs-on: ubuntu-latest
    if: github.event.issue.type.name == 'Epic'
    env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_NUM: github.event.issue.number
        ISSUE_URL: github.event.issue.html_url
        PARENT_URL: ${{ ISSUE_URL }}/sub_issues
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Create issue from file
        id: a11y-design
        run: |
          echo "CHILD=$(gh issue create --title "Totes auto-created" --body-file ".github/ISSUE_TEMPLATE/epics/test.md")" >> $GITHUB_ENV 
          echo "CHILD_ID=$(gh api $CHILD --jq .id)" >> $GITHUB_ENV
          echo "CHILD_NUM=$(gh api $CHILD --jq .number)" >> $GITHUB_ENV

      - name: Attach issue to to Epic
        run: |
          gh api -X POST $PARENT_URL -F sub_issue_id=$CHILD_ID
