name: Conditional subissues for Epic issues

on:
  issues:
    types: [opened]

permissions:
  issues: write
  
jobs:
  frontend-work:
    runs-on: ubuntu-latest
    if: github.event.issue.type.name == 'Epic'
    env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
        backend_only: ${{ steps.backend.outputs.backend_only }}
        admin_only: ${{ steps.admin.outputs.admin_only }}
        
    steps:
      - name: Check if epic is backend-only
        id: backend
        run: |
          match="$(${{ github.event.issue.body }} | grep -c -q "Backend-only")"
          if match > 0 ; then
            echo "backend_only=true" >> $GITHUB_ENV
          else
            echo "backend_only=false" >> $GITHUB_ENV
          fi
        
      - name: Check if epic is admin-only
        id: admin
        run: |
          match="$(${{ github.event.issue.body }} | grep -c -q "only- in the Admin")"
          if match > 0; then
            echo "admin_only=true">> "$GITHUB_ENV"
          else
            echo "admin_only=false">> "$GITHUB_ENV"
          fi

  subissues-tests:
      runs-on: ubuntu-latest
      needs: frontend-work
      if: ${{ needs.frontend-work.outputs.backend_only != 'true' && needs.frontend-work.outputs.admin_only != 'true' }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      steps:
      - name: Make a list of all markdown files from correct subdirectory
        env:
          DIRECTORY: steps.get_directory.outputs.dir
        run: | 
          {
            echo 'MY_FILELIST<<EOF'
            gh api --jq '.[].name' /repos/${{ github.repository }}/contents/.github/ISSUE_TEMPLATE/Epic | grep '.md'
            echo EOF
          } >> "$GITHUB_ENV"
        
  subissues-design:
      runs-on: ubuntu-latest
      needs: frontend-work
      if: ${{ needs.frontend-work.outputs.backend_only != 'true' }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      steps:
      - name: Define api call to add subissues
        run: echo "ADD_SUBISSUE_API=/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/sub_issues" >> $GITHUB_ENV

      - name: Save directory of subissues
        run: echo "SUBISSUE_DIR=.github/ISSUE_TEMPLATE/Design" >> $GITHUB_OUTPUT
      
      - name: Make or add to list of all markdown files from correct subdirectory
        run: | 
          {
            echo 'MY_FILELIST<<EOF'
            gh api --jq '.[].name' /repos/${{ github.repository }}/contents/.github/ISSUE_TEMPLATE/Design | grep '.md'
            echo EOF
          } >> "$GITHUB_ENV"

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create issue for each markdown file and attach as subissue to newly created epic
        run: |
          for file in $MY_FILELIST; do
            # set title to file name and remove file extension 
            TITLE=${file%%.*}
            # replace hyphens with spaces
            TITLE="${TITLE//-/ }"

            # create issue and get issue number
            CHILD=$(gh issue create --title "$TITLE" --body-file "${file}")
            CHILD_NUM=$(gh issue view $CHILD --json number --jq '.number')

            # get issue database id
            # source: https://jessehouwing.net/create-github-issue-hierarchy-using-the-api/
            CHILD_ID=$(gh api /repos/${{ github.repository }}/issues/$CHILD_NUM --jq .id)

            # add child to epic
            gh api -X POST $ADD_SUBISSUE_API -F sub_issue_id=$CHILD_ID

            # set issue type
            gh api -X PATCH /repos/${{ github.repository }}/issues/$CHILD_NUM --field type="Task" 
          done  
