name: Create subissues for Epic issues

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  create-subissues:
    runs-on: ubuntu-latest
    if: github.event.issue.type.name == 'Epic'
    steps:
      - name: Get Parent Numbers
        run: echo "PARENT_NUM=github.event.issue.number" >> $GITHUB_ENV
        
      - name: Checkout repo and get parent numbers
        uses: actions/checkout@v3
        
      - name: Create issue from file
        id: a11y-design
        run: |
          gh issue create \
            --title "Totes auto-created" \
            --body-file .github/ISSUE_TEMPLATE/epics/test.md"
          echo "CHILD=context.issue" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          
      - name: Attach issue to to Epic
        run: |

            // 2) Link the newly created issue as a sub-issue of the Epic
            await github.request('POST /repos/{owner}/{repo}/issues/{issue_number}/sub_issues', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ env.PARENT_NUM }},
              sub_issue_id: ${{ env.CHILD.id }}
            });

            console.log(`Linked created issue #${{ env.CHILD.number }} as a Task subissue of Epic #${{ env.PARENT_NUM }}`);
